language: go

go:
  - 1.8
  - master

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq
  - go get github.com/mattn/go-sqlite3
  - go get github.com/jteeuwen/go-bindata

before_script:
  - psql  -c "CREATE DATABASE gloat_test;" -U postgres
  - mysql -e 'CREATE DATABASE gloat_test;'

script:
  - make test

matrix:
  fast_finish: true
  allow_failures:
    - go: master

env:
  global:
    - DATABASE_SRC=testdata/migrations
  matrix:
    - DATABASE_URL='postgres://postgres@localhost/gloat_test?sslmode=disable'
    - DATABASE_URL='mysql://travis@tcp(127.0.0.1:3306)/gloat_test'
    - DATABASE_URL='sqlite3://:memory:'
